universe = docker
docker_image = jinnian/nas:rob-torch

log = test_swingen_$(Cluster).log
error = test_swingen_$(Cluster)_$(Process).err
output = test_swingen_$(Cluster)_$(Process).out

executable = run_swingen.sh
arguments = 1000 swin_gen_residual_attn $(Process)

should_transfer_files = YES
Requirements = (Target.HasCHTCStaging == true) && (CUDACapability >= 7.0)
when_to_transfer_output = ON_EXIT
+WantGPULab = true
+GPUJobLength = "medium"
+WantFlocking = true

request_gpus = 1
request_cpus = 1
request_memory = 5GB
request_disk = 15GB

queue 8